### ISSUE TITLE
System Init failed! with arduino uno

### ISSUE THREAD

**Issue by robomaniac** [stm32duino/X-NUCLEO-NFC04A1#10]
I got the X-NUCLEP-NFC0A1 and I can scan it with my phone. I get "_www.st.com_" This works.

I then plug the shield on my uno. I flash it, all the LED light up in sequence but serial port I get "System Init failed!"

The shield is plug so the 2 first pins are not plug into arduino. They left floating. I double check datasheet.

Also I have to comment out _**line 81**_ in the **_x_nucleo_nfc04a1.cpp_** because could not compile and UNUSED was not recognize.
```
void NFC04A1_LED_DeInit(NFC04A1_Led_E led)
{
  //UNUSED(led);
}
```

**Comment by mathiasconradt** [comment]
I'm having the same issue today, when I re-installed the Arduino IDE and reloaded my example program that I did last year. I recall that it worked fine around August 2019, so it must be something with the library update.
Looking at the commits, I see that there were 2 commits in March 2020 (since 2018). 

I just tried with version 1.0.2, which works (beside some common warning), so the issue is with the 1.1.0 version.

**Comment by fpistm** [comment]
Hi @robomaniac and @mathiasconradt 
I've tested on UNO and yes there is an issue anyway I was not able to get it work with 1.0.2 too.
Which Arduino IDE version you used and Arduino UNO model ?
I'm using latest Arduino IDE 1.8.12 and UNO R3.

**Comment by fpistm** [comment]
Hi @robomaniac and @mathiasconradt 
Issue is linked to the RAM usage. This library uses a lot of RAM that's why the default sketch does not run properly, usage of Serial and `read/WriteURI` API is too huge and does not allow to execute it properly. I've rework the example to not use Serial but only LED status.

I've also fixed the build issue linked to the `UNUSED `.
All the warnings has been fixed here:
https://github.com/stm32duino/ST25DV/pull/2

there is no dependency between the fixes.
